name: Validate Registry

on:
  pull_request:
    paths:
      - 'registry/**/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            registry/**/*.json
            
      - name: Validate PyPI packages
        id: validate
        run: python .github/scripts/validate_pypi.py
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Status Check
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const conclusion = process.env.VALIDATE_EXIT_CODE === '0' ? 'success' : 'failure';
            const title = conclusion === 'success' ? '✅ Registry 验证通过' : '❌ Registry 验证失败';
            const summary = conclusion === 'success' 
              ? '所有检查项目均已通过，可以继续合并。' 
              : '发现问题，请查看评论了解详情。';
            
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Registry Validation',
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: conclusion,
              output: {
                title: title,
                summary: summary
              }
            });
        env:
          VALIDATE_EXIT_CODE: ${{ steps.validate.outcome == 'success' && '0' || '1' }} 